spring.application.name=blog

spring.datasource.url=jdbc:postgresql://localhost:5433/blog
spring.datasource.username=blog
spring.datasource.password=blog

spring.flyway.url=jdbc:postgresql://localhost:5433/blog
spring.flyway.user=blog
spring.flyway.password=blog

spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.serialization-mode=via_dto
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.mvc.servlet.path=/api

jwt.secret.key=ukmg5rhyf8LmrgEuy3N5f8qQmozPeSl6k7sKyN4b1Sl